// layout.tsx (server component)
import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { FooterSection } from "@/components/Footer";




export const metadata: Metadata = {
  title: "Hospital Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased">
       
        <Navbar />
          {children}
          <FooterSection />
        
      </body>
    </html>
  );
}
